# Generated by Django 6.0.3 on 2026-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
