# Generated by Django 6.0.3 on 2026-04-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_intern_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='age',
        ),
    ]
